import java.util.ArrayList;
import java.util.List;

import outils.Node;
import outils.Sequence;
import outils.TypeSeq;
import outils.Upgma;


public class Main {
    public static void main(String[] args) throws Exception {
        //initialise sequences
        // Sequence seq1 = new Sequence("seq1", "ATGC", TypeSeq.ADN);
        // Sequence seq2 = new Sequence("seq2", "TTGC", TypeSeq.ADN);
        // Sequence seq3 = new Sequence("seq3", "ACCG", TypeSeq.ADN);
        // Sequence seq4 = new Sequence("seq4", "TACG", TypeSeq.ADN);
        // //initialise liste sequence
        // ArrayList<Sequence> listSeq = new ArrayList<Sequence>(List.of(seq1,seq2,seq3,seq4));
        // //initialise matrice distance et liste noeud
        // Float[][] matriceD = new Float[listSeq.size()][listSeq.size()];
        // ArrayList<Node> listNoeud = new ArrayList<Node>();
        
        //test 2
        // Sequence seqA = new Sequence("seqA", "ATCGTGGTACTG", TypeSeq.ADN);
        // Sequence seqB = new Sequence("seqB", "CCGGAGAACTAG", TypeSeq.ADN);
        // Sequence seqC = new Sequence("seqC", "AACGTGCTACTG", TypeSeq.ADN);
        // Sequence seqD = new Sequence("seqD", "ATGGTGAAAGTG", TypeSeq.ADN);
        // Sequence seqE = new Sequence("seqE", "CCGGAAAACTTG", TypeSeq.ADN);
        // Sequence seqF = new Sequence("seqF", "TGGCCCTGTATC", TypeSeq.ADN);

        // //initialise liste sequence
        // ArrayList<Sequence> listSeq2 = new ArrayList<Sequence>(List.of(seqA,seqB,seqC,seqD, seqE, seqF));
        // //initialise matrice distance et liste noeud
        // Float[][] matriceD2 = new Float[listSeq2.size()][listSeq2.size()];
        // ArrayList<Node> listNoeud2 = new ArrayList<Node>();

        //test 3
        Sequence HIV_1_group_N = new Sequence("HIV_1_group_N", "-------------ATGGGAACAGAGCTTAAAGCCCTGTGTTAAATTAA-CCCCA----TTATGTGTAA-----CTATGCTTTGTAACAATAGCAATGGG-------AATAGTGCAGGGAATAGTACT------------ACCAATAGGA---C-AGAGGATCTAGAAGACAGACAAAT---------------------GAA-----AAATTGCTCATTCAATATAACCACTGAGATAAGAGATAGAAAGAAGCAAGTTTACTCTCTGTTTTATGTAGAAGATGTAGTGCCAATCAAAGATGGGACTGACAATAATACATATAG-GCTAATAAATTGTAATACCACAGCTGTGACACAAGCTTGTCCTAAGAC", TypeSeq.ADN);
        Sequence HIV_1_group_O = new Sequence("HIV_1_group_O", "---GGTAGAACAAATGCAGGAAGACATTATTAGCTTATGGGAACAGAG-CTTCAAACCTTGTGTGCAA-----ATGACTTTTCTGTGTGTACAAATGA--------ATTGTCACATTGTAGAAGAA-------------ACCAACAGCT---C-A------TCAGCAGAGAAACCTTT---------------------ACA-----A---TGTGAGTTTAATGTAACCACTGTTGTCAAGGACAAAAAAGAGAAAAAACAGGCTCTATTTTATAGATCAGATTTAATGAAATT---AGATGAAACAAACGAAACAATGTATAC-ATTAATTAATTGTAACTCCACAACCATTAAGCAAGCCTGTCCAAAGAT", TypeSeq.ADN);
        Sequence HIV_1_subtype_A = new Sequence("HIV_1_subtype_A", "------AGAGCAGATGCATACAGATATAATCAGTCTATGGGATCAGAG-CCTAAAGCCATGTGTAGAA-----TTAACCCCTCTCTGCGTTACTTTAGATTGTCTAAACGCCACCCTCAATGCCACC------------GCCCCCAATG---T-CACCAATGACATGGAAGGAGAAAT---------------------GAA-----AAACTGCTCTTACAATATAACCACAGAATTAAAGGATAAGAAACAGCAAGTGTATTCACTTTTTTATAAGCTTGATGTAGTACAAATTAATGAAAAGAATAAAACAAACAAGTATAG-ATTAATAAATTGTAATACCTCAGCCATTAC------------------", TypeSeq.ADN);
        Sequence HIV_1_subtype_B = new Sequence("HIV_1_subtype_B", "------AGAGCAGATGCAGGAGGATGTAATCAGTTTATGGGATCAAAG-TCTAAAGCCATGTGTAAAA-----TTAACTCCTCTCTGCGTTACTTTACATTGTACCAATGTCTCTTTAAATAGTACCAATGCAAATTATACCAGTGACT---CTAAAGGAATCGGAAATATAACAGAT---------------------GAAGCAAGAAACTGTTCTTTTAATATAACCACAGAATTAATAGATAAGAAGCAGAAAGTTTATGCACTTTTTTATAAGCTTGATATAGTACAAAT---GGGAGATAATAATAGTAGTGAGTATAG-ATTAATAAATTGTAA---------------------------------", TypeSeq.ADN);
        Sequence HIV_1_subtype_C = new Sequence("HIV_1_subtype_C", "------GGATCAGATGCATGAGGATATAATCAGTTTATGGGATGAAAG-CCTAAAGCCATGTGTAACG-----TTAACCCCACTCTGTGTCACTTTATATTGTAGTAATGTTAATAATACCAGTAGTAATGTTAATAGTACCAGTAGTAATGTTAATAGTACCAGTAATGGTAATGATACCACCCAGGAGGGCATAGAAGAGATAAAAAATTGCTCTTTCAATGCAACCACAGAAATAAAAGATAAGCACCGGAAAGAGCATGCACTTTTTTATAGACTAGACATAGTGCCAATTAGTAATAACACCTATAG-------------------------------------------------------------", TypeSeq.ADN);
        Sequence HIV_1_subtype_D = new Sequence("HIV_1_subtype_D", "------GGAGCAGATGCATGAGGATATCATCAGTTTATGGGATCAAAG-CCTAAAACCATGTGTAAAA-----TTAACCCCACTCTGTGTCACTTTAAACTGCACTGATGCAAGGAGGAATGAGACT------------AGGAATAATA---CAGGAATGGAAAACAATGATCAAATA---------------------GAAATGAAAAACTGCTCTTTCAATATAACCACAAAATTAATAGATAAGAAGAAGCAAGTACATGCACTTTTTTATAGACTTGATGTGGTACAAATAGATAATGAGACTAGTAATAGCAACTATAGCAACTATAGATTAATAAATTGCAA-------------------------", TypeSeq.ADN);
        Sequence HIV_2_subtype_A = new Sequence("HIV_2_subtype_A", "---TGTCAAGTTAACACCCTTATGTGTAGTAATGAACTGTAGCAAACTCAGTAACACTGCAAATACAACAGCTGCACCCACAGCAAACGCAACAACCACAT-CCGCAAACACAACAACCACAACAACAAAAAATGT--ATGGATAAATGAGACTTCTCCATGCATGCGCGCAGACAACTGCTCAGGATTAGGGGGGGAAGAGATGGTCACTTGTCACTTCAATATGACAGGGTTAGAGAGAGATAAGAAAAAGGCGTATAATGAAACATGGTACTCAAAGGATGTAGTATGTGA---ATATGAAAACCA----------------------------------------------------------------", TypeSeq.ADN);
        Sequence HIV_2_subtype_B = new Sequence("HIV_2_subtype_B", "ATGTGTTAAATTAACCCCACTATGTGTAACAATGAATTGTAGTAACCT---TAACA---------------------CCACAGCCAACACCACCACAGC---CAACAACATCACAGCCTCTAAGAACATAAGTA------TGCTCAATGGAAATGACTCATGTATCCGAGATGACAACTGCACAGGTATAGAATTTGAGAACATGGTAACATGTCGATTCAATATGACAGGATTAAAAGTAGATGAACCGAAAACGTATAATGACACCTGGTATGCAGAAGATGTACAGTGTAAT--GGGAGCAGATGCCATATAAAAACCTGTAACACATCAAT--------------------------------------", TypeSeq.ADN);
        Sequence SIV_chpz = new Sequence("SIV_chpz", "------GTCACAAATGCAAGAAGATATCATTAGCCTATGGGAGCAAAG-TCTAAAGCCATGTGTAAAG-----TTAACCCCTTTATGTGTAACTCTAAATTGCTCTACTGCTATTTTTAGAGCAAACAGGAC------TAGCACCAACACAACTACACCTAGCACCATCGCAACTAGTCCTACAACTGATACAATTTATGAAATGAAAAATTGCTCTTTTAATGTAACAACAGAATTAAGGGATAAAAAGAAACAGGTATATTCTTTATTTTATGTAGATGATGTAGTGAAACTTAATGATGGAGATTCAACAAATAG-------------------------------------------------------", TypeSeq.ADN);
        Sequence SIV_mac = new Sequence("SIV_mac", "TTGTGTAAAATTATCCCCATTATGCATTACTATGAGATGCAATAAA---AGTGAGA---CAGATAGATGGGGATTGACAAAATCAATAACAACAACAGCAT-CAACAACATCAACGACAGCATCAGCAAGAGTAGA--CATGGTCAATGAGACTAGTTCTTGTATAGCCCAGGATAATTGCGCAGGCTTGGAACAAGAGCAAATGATAAGCTGTAAATTCAACATGACAGGGTTAAATAGAGACAAGAAAAAAGAGTACAATGAAACCTGGTACTCTGCAGATTTGGTATGTGA---ACAAGGGAATAACAC-------------------------------------------------------------", TypeSeq.ADN);

        //initialise liste sequence
        ArrayList<Sequence> listSeq3 = new ArrayList<Sequence>(List.of(HIV_1_group_N, HIV_1_group_O, HIV_1_subtype_A, HIV_1_subtype_B, HIV_1_subtype_C, HIV_1_subtype_D, HIV_2_subtype_A, HIV_2_subtype_B, SIV_chpz, SIV_mac));
        //initialise matrice distance et liste noeud
        Float[][] matriceD3 = new Float[listSeq3.size()][listSeq3.size()];
        ArrayList<Node> listNoeud3 = new ArrayList<Node>();

        Upgma resultUpgma = new Upgma(listSeq3, matriceD3, listNoeud3);        
    }

}